name: Exemplo Triggers
run-name: Exemplo workflow para Triggers, executado por ${{ github.actor }}
# on:
#     workflow_dispatch:
on:
    push:
        branches: ["main", "feature/*"]
        paths:
            - "src/**"
jobs:
    usando_triggers:
        runs-on: ubuntu-latest
        steps:
            - name: 'Uso de triggers'
              run: ls -lha