name: Exemplo Functions
run-name: Exemplo workflow para Functions, executado por ${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            versao:
                type: string
                required: true
                default: "dev"
                description: "Versão da nova release"
            numero_card:
                type: number
                required: true
                description: "Número do card da tarefa desse commit"
            fazer_deploy:
                type: boolean
                required: true
                description: "Fazer deploy ou não"
            ambiente:
                type: choice
                required: true
                description: "Ambiente de Deploy"
                options:
                    - DEV
                    - HML
                    - PRD
jobs:
    valores_input:
        runs-on: ubuntu-latest
        steps:
            - name: 'Função contains'
              run: echo "${{ contains(inputs.ambiente, github.actor) }}"