name: Exemplo Triggers
run-name: Exemplo workflow para Triggers, executado por ${{ github.actor }}
on:
    workflow_dispatch:
# on:
#     push:
#         branches: ["main", "feature/*"]
#         paths:
#             - "src/**"
# on:
#     pull_request:
#         branches: ["main"]
#         types:
#             - closed
# on:
#     schedule:
#         - cron: "*/2 * * * *"
jobs:
    usando_triggers:
        runs-on: ubuntu-latest
        steps:
            - name: 'Uso de triggers'
              run: ls -lha