name: Controle de Fluxo por job
run-name: Exemplo workflow para Controle de Fluxo por job, executado por ${{ github.actor }}
on:
    push:
jobs:
    exemplo-fluxo-01:
        runs-on: ubuntu-latest
        steps:
            - name: Esse vai falhar
              run: 1

    exemplo-fluxo-02:
        runs-on: ubuntu-latest
        needs: [exemplo-fluxo-01]
        if: ${{ success() || failure() }}
        steps:
            - name: Execucao com sucesso
              run: echo "Executando de fluxo"