name: Exemplo Operadores
run-name: Exemplo workflow para Operadores, executado por ${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            valor_numerico:
                type: number
                default: 1
            valor_string:
                type: string
                default: "Valor XPTO"
            valor_boolean:
                type: boolean
                default: true
jobs:
    usando_operadores:
        runs-on: ubuntu-latest
        steps:
            - name: 'Operacao com String'
              run: echo "${{ github.actor == inputs.valor_string }}"
            - name: 'Operacao com Number'
              run: echo "${{ inputs.valor_numerico > 20 }}"
            - name: 'Operacao com Boolean'
              run: echo "${{ !inputs.valor_boolean }}"