name: Condicional status
run-name: Exemplo workflow para Coondicional status, executado por ${{ github.actor }}
on:
    #push:
    workflow_dispatch:
jobs:
    apenas-main:
        if: ${{ github.ref == 'refs/heads/main' }}
        name: esse job s√≥ roda na branch main
        runs-on: ubuntu-latest
        steps:
            - name: Executando na main
              run: echo "Executando comando na main"

    todos:
        runs-on: ubuntu-latest
        steps:
            - name: Executando em feature
              if: ${{ contains(github.ref, 'refs/heads/feature') }}
              run: echo "Executando comando na feature"
            - name: Executando em hotfix
              if: ${{ contains(github.ref, 'refs/heads/hotfix') }}
              run: echo "Executando em hotfix"
            - name: Executando job
              run: ech "Executando comando"
            - name: Envio de erros
              if: ${{ failure() }}
              run: echo "Envia email"